# Generated by Django 5.0.2 on 2024-04-01 13:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.TextField(blank=True, default='User Bio')),
                ('contact', models.TextField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Datacard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_name', models.CharField(default='N/A', max_length=100)),
                ('identifier', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField(default='N/A')),
                ('motivation', models.TextField(default='N/A')),
                ('dataset_accessibility', models.CharField(default='N/A', max_length=100)),
                ('accessibility_info', models.TextField(default='N/A')),
                ('research_motivation', models.TextField(default='N/A')),
                ('authors', models.TextField(default='N/A')),
                ('contributors', models.TextField(default='N/A')),
                ('funding_type', models.CharField(default='N/A', max_length=100)),
                ('funding_info', models.TextField(default='N/A')),
                ('is_combination', models.BooleanField(default=False)),
                ('combination_info', models.TextField(blank=True, null=True)),
                ('date_created', models.TextField(default='N/A')),
                ('version', models.CharField(default='N/A', max_length=20)),
                ('applications', models.TextField(default='N/A')),
                ('datatypes', models.TextField(default='N/A')),
                ('primary_data', models.CharField(default='N/A', max_length=100)),
                ('annotation_method', models.CharField(default='N/A', max_length=100)),
                ('annotation_info', models.TextField(default='N/A')),
                ('collection', models.TextField(default='N/A')),
                ('size', models.TextField(default='N/A')),
                ('personal_data', models.CharField(default='N/A', max_length=100)),
                ('flaws', models.TextField(default='N/A')),
                ('data_splits', models.TextField(default='N/A')),
                ('dataset_format', models.CharField(default='N/A', max_length=100)),
                ('languages', models.TextField(default='N/A')),
                ('doi', models.CharField(default='N/A', max_length=100)),
                ('licence', models.CharField(default='N/A', max_length=100)),
                ('last_update', models.TextField(default='N/A')),
                ('is_maintained', models.BooleanField(default=False)),
                ('maintenance_info', models.TextField(blank=True, default='N/A', max_length=1000)),
                ('possible_uses', models.TextField(default='N/A')),
                ('unsafe_applications', models.TextField(default='N/A')),
                ('bias_problems', models.TextField(default='N/A')),
                ('social_impact', models.TextField(default='N/A')),
                ('dataset_citation', models.TextField(default='N/A')),
                ('additional_information', models.TextField(blank=True, default='N/A')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
