# Generated by Django 5.0.2 on 2024-03-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacard',
            name='additional_information',
            field=models.TextField(blank=True, default='N/A'),
        ),
        migrations.AddField(
            model_name='datacard',
            name='annotation_info',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='datacard',
            name='annotation_method',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='datacard',
            name='applications',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='datacard',
            name='bias_problems',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='datacard',
            name='collection',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='datacard',
            name='data_splits',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='datacard',
            name='dataset_citation',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='datacard',
            name='dataset_format',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='datacard',
            name='datatypes',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='datacard',
            name='doi',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='datacard',
            name='flaws',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='datacard',
            name='is_maintained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datacard',
            name='languages',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='datacard',
            name='last_update',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='datacard',
            name='licence',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='datacard',
            name='maintenance_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datacard',
            name='personal_data',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='datacard',
            name='possible_uses',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='datacard',
            name='primary_data',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='datacard',
            name='size',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='datacard',
            name='social_impact',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='datacard',
            name='unsafe_applications',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='datacard',
            name='accessibility_info',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='datacard',
            name='authors',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='datacard',
            name='contributors',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='datacard',
            name='dataset_accessibility',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='datacard',
            name='dataset_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='datacard',
            name='date_created',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='datacard',
            name='description',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='datacard',
            name='funding_info',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='datacard',
            name='funding_type',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='datacard',
            name='motivation',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='datacard',
            name='research_motivation',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='datacard',
            name='version',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
