from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.conf import settings


class CustomUser(AbstractUser):
    bio = models.TextField(blank = True, default = "User Bio")
    contact = models.TextField(blank = True)

class Datacard(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    dataset_name = models.CharField(max_length=100, default= "N/A")
    identifier = models.CharField(max_length=400, blank=True)
    description = models.TextField(default= "N/A")
    motivation = models.TextField(default= "N/A")
    dataset_accessibility = models.CharField(max_length=100, default= "N/A")
    accessibility_info = models.TextField(default= "N/A")
    research_motivation = models.TextField(default= "N/A")
    authors = models.TextField(default= "N/A")
    contributors = models.TextField(default= "N/A")
    funding_type = models.CharField(max_length=100, default= "N/A")
    funding_info = models.TextField(default= "N/A")
    is_combination = models.BooleanField(default=False)
    combination_info = models.TextField(blank=True, null=True)
    date_created = models.TextField(default= "N/A")
    version = models.CharField(max_length=20, default= "N/A")
    applications = models.TextField(default= "N/A")
    datatypes = models.TextField(default= "N/A")
    primary_data = models.CharField(max_length=100, default= "N/A")
    annotation_method = models.CharField(max_length=100, default= "N/A")
    annotation_info = models.TextField(default= "N/A")
    collection = models.TextField(default= "N/A")
    size = models.TextField(default= "N/A")
    personal_data = models.CharField(max_length=100, default= "N/A")
    flaws = models.TextField(default= "N/A")
    data_splits = models.TextField(default= "N/A")
    dataset_format = models.CharField(max_length=100, default= "N/A")
    languages = models.TextField(default= "N/A")
    doi = models.CharField(max_length=100, default= "N/A")
    licence = models.CharField(max_length=100, default= "N/A")
    last_update = models.TextField(default= "N/A")
    is_maintained = models.BooleanField(default=False)
    maintenance_info = models.TextField(max_length=1000, blank=True, default = 'N/A')
    possible_uses = models.TextField(default= "N/A")
    unsafe_applications = models.TextField(default= "N/A")
    bias_problems = models.TextField(default= "N/A")
    social_impact = models.TextField(default= "N/A")
    dataset_citation = models.TextField(default= "N/A")
    additional_information = models.TextField(blank=True, default= "N/A")
